config/routes.rb
Rails.application.routes.draw do
  root to: 'entries#index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  
  resources :entries
  get "/archive",   to: 'entries#archive'
  get "/thisweek",  to: 'entries#thisweek'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord

  belongs_to :user

  scope :by_user, lambda { |user|
    where(:user_id => user.id)
  }
  scope :today, -> { 
    where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) 
  }
  scope :thisweek, -> { 
    where(created_at: DateTime.now.beginning_of_week..DateTime.now) 
  }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :entries
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_entry, only: [:edit, :show, :update, :destroy]

  def index
    @total_minutes = Entry.select(:minutes_read).map(&:minutes_read).inject(0, :+)
    @total_pages = Entry.select(:pages_read).map(&:pages_read).inject(0, :+)
    @total_books = Entry.select(:pages_read).map(&:pages_read).uniq
    @today_minutes = Entry.today.by_user(current_user).select(:minutes_read).map(&:minutes_read).inject(0, :+)
    @entries_today = Entry.today.by_user(current_user).order('created_at DESC')
  end

  def edit
    @books = Entry.select(:book_title).map(&:book_title)
  end

  def show
  end

  def new
    @books = Entry.select(:book_title).map(&:book_title)
    @entry = Entry.new
  end

  def create
    @entry = Entry.new(entry_params)
    if @entry.save
      redirect_to root_path, notice: "I added your progress. Good job!"
    else
      render 'new'
    end
  end

  def update
    @entry = Entry.find(params[:id])
    if @entry.update(entry_params)
      redirect_to root_path, notice: "I updated your progress!"
    else
      render 'new'
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    redirect_to root_path, notice: "I deleted that status."
  end

  # /archive
  def archive
    @this_user = current_user.id
    @entries = Entry.by_user(current_user).all.order('created_at DESC')
  end

  # /thisweek
  def thisweek
    @this_user = current_user.id
    @week_minutes = Entry.thisweek.select(:minutes_read).map(&:minutes_read).inject(0, :+)
    @entries = Entry.by_user(current_user).thisweek.all.order('created_at ASC')
  end

  private

    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params.require(:entry).permit(:book_title, :genre, :pages_read, :genre, :minutes_read, :user_id)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:fname, :lname, :email, :reading_goal_minutes, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:fname, :lname, :email, :reading_goal_minutes, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_class?(test_path)
    return 'active' if request.path == test_path
    ''
  end

  def total_minutes
    @total_minutes = Entry.select(:minutes_read).map(&:minutes_read).inject(0, :+)
    return @total_minutes
  end

  def total_pages
    @total_pages = Entry.select(:pages_read).map(&:pages_read).inject(0, :+)
    return @total_pages
  end

  def total_books
    @total_books = Entry.select(:pages_read).map(&:pages_read).uniq
    return @total_books
  end

  def minutes_today
    @minutes_today = Entry.today.select(:minutes_read).map(&:minutes_read).inject(0, :+)
    return @minutes_today
  end

  def goal_seek(goal, actual)
    @percent_complete = (goal / actual) * 100
    return @percent_complete.to_i
  end
  
end

app/views/entries/_entry.html.erb
<div class="entries__item">
  <% if local_assigns[:timestamp] %>
    <div class="time-stamp">
      <%= entry.created_at.strftime("%A %l:%M %p") %>
    </div>
  <% end %>
  <div class="edit-this">
    <%= link_to raw('<i class="fa fa-trash"></i>'), entry, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
  </div>
  <h1><%= link_to entry.book_title, entry %></h1>
  <div class="stats">
    <div class="stats__item">
      <h2>
        <%= entry.pages_read %>
        <small>Pages Read</small>
      </h2>
    </div>
    <div class="stats__item">
      <h2>
        <%= entry.minutes_read %>
        <small>Minutes Read</small>
      </h2>
    </div>
  </div>
</div>

app/views/entries/_form.html.erb
<%= form_for @entry do |f| %>

  <p>
    <%= f.text_field :book_title, required: true, placeholder: "ex. Charlotte's Web" %>
    <label><%= f.label :book_title %></label>
  </p>

  <p>
    <%= f.text_field :genre, required: true, placeholder: "ex. Historical Fiction" %>
    <label><%= f.label :genre %></label>
  </p>

  <p>
    <%= f.text_field :pages_read, required: true %>
    <label><%= f.label :pages_read %></label>
  </p>

  <p>
    <%= f.number_field :minutes_read, required: true %>
    <label><%= f.label :minutes_read %></label>
  </p>

  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit "Add Progress", class: "btn" %>
<% end %>

app/views/entries/archive.html.erb
<header class="main">
  <h1>All Entries</h1>
  <h3><%= pluralize(@entries.count, 'Entry') %></h3>
  <%=link_to 'New', "#", class: 'add-new-entry new' %>
</header>

<div class="add-bottom-space">
  <% if @entries.empty? %>
    <div class="gentle-nudge">
      <div class="gentle-nudge__text">
        <h5 class="is-centered is-padded">
          No entries.
          <%=link_to "Get Started!", new_entry_path, class: 'btn btn--simple new' %>
        </h5>
      </div>
    </div>
  <% else %>
    <div class="entries">
      <%= render :partial => 'entry', :collection => @entries %>
    </div>
  <% end %>
</div>

app/views/entries/edit.html.erb
<header class="sub sub--blue">
  <div class="chevron">
    <%= link_to :back do %>
      <%=fa_icon "chevron-left" %>
    <% end %>
  </div>
  <h4 class="is-centered"><%= @entry.created_at.strftime("%b %d, %Y") %></h4>
  <div class="edit">
    <%=link_to "Edit", edit_entry_path %>
  </div>
</header>

<%= render 'form' %>

app/views/entries/index.html.erb
<% if user_signed_in? %>
  <header class="main">
    <h1>Today</h1>
    <h3>
      <%= pluralize(@entries_today.count, 'Entry') %>,
      <%= current_user.reading_goal_minutes.to_i %> Minute Goal
    </h3>
    <%=link_to 'New', "#", class: 'add-new-entry new' %>
  </header>

  <div class="add-bottom-space">
    <% if @entries_today.empty? %>
      <div class="gentle-nudge">
        <div class="gentle-nudge__text">
          <h5 class="is-centered is-padded">
            No entries for today. 😕
            <%=link_to "Add Now", new_entry_path, class: 'btn btn--simple new' %>
          </h5>
        </div>
      </div>
    <% else %>
      <div class="entries">
        <%= render :partial => 'entry', :collection => @entries_today %>
      </div>
    <% end %>

    <h5 class="glance is-centered">
      <%= @today_minutes %> of <%= current_user.reading_goal_minutes.to_i %> Minutes
      (<%= goal_seek(@today_minutes, current_user.reading_goal_minutes) %>%)
    </h5>
  </div>
<% else %>
  <header class="main">
    <h1>Today</h1>
    <h3>
      Today's reading goal progress
    </h3>
  </header>

  <div class="gentle-nudge">
    <div class="gentle-nudge__text">
      <main>👋</main>
      <h1>Hello friend!</h1>
      <h2>Today's reading will be here after you <%=link_to "sign up", new_user_registration_path %> or <%=link_to "log in", new_user_session_path %>.</h2>
    </div>
  </div>

<% end %>

app/views/entries/new.html.erb
<header class="main">
  <h1>New Log</h1>
  <h3>Log your reading</h3>
</header>

<%= render 'form' %>

app/views/entries/show.html.erb
<div class="book add-bottom-space">

  <header class="sub">
    <div class="chevron">
      <%= link_to :back do %>
        <%=fa_icon "chevron-left" %>
      <% end %>
    </div>
    <h4 class="is-centered"><%= @entry.created_at.strftime("%b %d, %Y") %></h4>
    <div class="edit">
      <%=link_to "Edit", edit_entry_path %>
    </div>
  </header>
  
  <div class="book__title">
    <h1 class="book-title is-centered" data-title="<%= @entry.book_title %>">
      <%= @entry.book_title %>
    </h1>
    <h4 class="author-field is-centered">
    </h4>

    <div class="book__stats">
      <div class="book__stats__item">
        <div class="book__stats__item--count">
          <%= @entry.pages_read %>
        </div>
        <h3>Pages Read</h3>
      </div>
      <div class="book__stats__item">
        <div class="book__stats__item--count">
          <%= @entry.minutes_read %>
        </div>
        <h3>Minutes Read</h3>
      </div>
    </div>

  </div>

  <div class="book__desc">
    <h4>
    </h4>
  </div>

</div>

app/views/entries/thisweek.html.erb
<header class="main">
  <h1>This Week</h1>
  <h3>
    <%= pluralize(@entries.count, 'Entry') %>,
    <%= pluralize(@week_minutes, 'Minutes') %>
  </h3>
  <%=link_to 'New', "#", class: 'add-new-entry new' %>
</header>

<div class="add-bottom-space">
  <% if @entries.empty? %>
    <div class="gentle-nudge">
      <div class="gentle-nudge__text">
        <h5 class="is-centered is-padded">
          No entries this week.
          <%=link_to "Get Started!", new_entry_path, class: 'btn btn--simple new' %>
        </h5>
      </div>
    </div>
  <% else %>
    <div class="entries">
      <%= render :partial => 'entry', :collection => @entries, locals: { timestamp: true } %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Readinglog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name='viewport' content='viewport-fit=cover, width=device-width, height=device-height, initial-scale=1.0, user-scalable=no'>
    <%= render 'shared/webcapable' %>
  </head>

  <body ontouchstart="">
    <%= render 'shared/navigation' %>

    <div class="view">
      <div class="content">
        <%= yield %>
      </div>
    </div>

    <%= render 'shared/overlay' %>
  </body>
</html>

app/views/shared/_alert.html.erb
  <div class="messaging">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
  </div>

app/views/shared/_form.html.erb
<%= form_for Entry.new do |f| %>

  <p>
    <%= f.text_field :book_title, required: true, placeholder: "ex. Charlotte's Web" %>
    <label><%= f.label :book_title %></label>
  </p>

  <p>
    <%= f.text_field :genre, required: true, placeholder: "ex. Historical Fiction" %>
    <label><%= f.label :genre %></label>
  </p>

  <p>
    <%= f.text_field :pages_read, required: true %>
    <label><%= f.label :pages_read %></label>
  </p>

  <p>
    <%= f.number_field :minutes_read, required: true %>
    <label><%= f.label :minutes_read %></label>
  </p>

  <% if user_signed_in? %>
    <!-- we have to check, or the resting screen throws an error -->
    <%= f.hidden_field :user_id, value: current_user.id %>
  <% end %>
  <%= f.submit "Add Progress", class: "btn" %>
<% end %>

app/views/shared/_navigation.html.erb
<!-- anchored iOS-style navBar -->
<nav class="navBar">

  <li class="navBar__entry <%= current_class?(root_path) %>">
    <%=link_to root_path do %>
      <span class="icon">
        <%= fa_icon "calendar" %>
      </span>
      <h3>Today</h3>
    <% end %>
  </li>

  <li class="navBar__entry <%= current_class?(archive_path) %>">
    <%=link_to archive_path do %>
      <span class="icon">
        <%= fa_icon "archive" %>
      </span>
      <h3>All Entries</h3>
    <% end %>
  </li>

  <li class="navBar__entry <%= current_class?(thisweek_path) %>">
    <%=link_to thisweek_path do %>
      <span class="icon">
        <%= fa_icon "check" %>
      </span>
      <h3>This Week</h3>
    <% end %>
  </li>

  <li class="navBar__entry <%= current_class?('/users/edit') %>">
    <%=link_to edit_user_registration_path do %>
      <span class="icon">
        <%= fa_icon "cog" %>
      </span>
      <h3>Profile</h3>
    <% end %>
  </li>

</nav>

app/views/shared/_overlay.html.erb
<div class="overlay"></div>
<div class="new-form">
  <div class="close">&times;</div>
  <%= render 'shared/form' %>
</div>

app/views/shared/_stats.html.erb
<div class="stats">
  <div class="stats__item">
    <h1><%= @total_minutes/60 %></h1>
    <h3>Total Hours Read</h3>
  </div>
  <div class="stats__item">
    <h1><%= @total_pages %></h1>
    <h3>Total Pages Read</h3>
  </div>
  <div class="stats__item">
    <h1><%= @total_books.length %></h1>
    <h3>Book Titles Read</h3>
  </div>
</div>

app/views/shared/_webcapable.html.erb
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="white-translucent">
<meta name="apple-mobile-web-app-title" content="Ruby Reader">
<!-- splash screen -->
<link rel="apple-touch-startup-image" href="/apple-launch-1125-2436.png">
<!-- icons -->
<link rel="apple-touch-icon" sizes="152x152" href="/152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="180x180.png">
<link rel="apple-touch-icon" sizes="167x167" href="167x167.png">